<template>
  <div class="page">
    <div class="page-heading"><div><h1>时效与日程</h1><p>对仲裁时效、材料提交和开庭日期进行统一提醒。</p></div><button class="primary-action"><i class="fa-solid fa-plus"></i> 添加日程</button></div>
    <div class="deadline-grid">
      <section class="panel calendar"><div class="calendar-head"><button><i class="fa-solid fa-chevron-left"></i></button><h2>2026 年 9 月</h2><button><i class="fa-solid fa-chevron-right"></i></button></div><div class="week"><span v-for="d in ['一','二','三','四','五','六','日']" :key="d">周{{d}}</span></div><div class="days"><span v-for="d in 35" :key="d" :class="{muted:d<2||d>31,today:d===17,event:[19,22].includes(d),court:d===8}">{{ d===1?'31':d>31?d-31:d }}</span></div><div class="legend"><span><i class="red"></i>紧急节点</span><span><i class="teal"></i>材料任务</span><span><i class="navy"></i>开庭</span></div></section>
      <section class="agenda"><div class="section-title"><h2>近期安排</h2><button class="text-button">按案件筛选</button></div><article v-for="item in agenda" :key="item.title" class="panel agenda-item"><div class="date-block" :class="item.tone"><strong>{{item.day}}</strong><small>{{item.month}}</small></div><div><span class="status" :class="item.status">{{item.type}}</span><h3>{{item.title}}</h3><p>{{item.case}}</p><small><i class="fa-regular fa-clock"></i> {{item.time}}　<i class="fa-solid fa-location-dot"></i> {{item.location}}</small></div><button><i class="fa-solid fa-ellipsis"></i></button></article></section>
    </div>
  </div>
</template>
<script setup>const agenda=[{day:'19',month:'9月',type:'法定时限',title:'提交仲裁申请材料',case:'PL-2026-017 · 违法解除劳动合同',time:'18:00 前',location:'深圳市劳动人事争议仲裁院',tone:'red',status:'danger'},{day:'22',month:'9月',type:'材料任务',title:'补充工资流水及考勤记录',case:'PL-2026-018 · 工资及加班费争议',time:'全天',location:'线上材料库',tone:'teal',status:'progress'},{day:'08',month:'10月',type:'开庭',title:'工伤待遇争议开庭',case:'PL-2026-015 · 工伤待遇争议',time:'09:30',location:'宁波市劳动人事争议仲裁院',tone:'navy',status:'done'}]</script>
<style scoped>.deadline-grid{display:grid;grid-template-columns:minmax(450px,1.15fr) minmax(360px,.85fr);gap:22px}.calendar{padding:22px}.calendar-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:22px}.calendar-head h2{margin:0;font-size:18px}.calendar-head button{width:34px;height:34px;border:1px solid var(--line);border-radius:8px;background:#fff}.week,.days{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.week span{padding:8px;color:#8995a2;text-align:center;font-size:10px}.days span{position:relative;min-height:62px;padding:9px;border-radius:9px;background:#f8fafb;font-size:11px}.days span.muted{color:#bdc5ce;background:transparent}.days span.today{box-shadow:inset 0 0 0 2px var(--teal);font-weight:700}.days span.event:after,.days span.court:after{content:'';position:absolute;left:9px;bottom:9px;width:6px;height:6px;border-radius:50%;background:#ce4552}.days span.court:after{background:#315d8a}.legend{display:flex;gap:18px;margin-top:18px;padding-top:14px;border-top:1px solid var(--line);color:#758293;font-size:9px}.legend i{display:inline-block;width:7px;height:7px;margin-right:5px;border-radius:50%}.legend .red{background:#ce4552}.legend .teal{background:var(--teal)}.legend .navy{background:#315d8a}.agenda-item{display:grid;grid-template-columns:54px 1fr 20px;gap:14px;margin-bottom:10px;padding:16px;box-shadow:none}.date-block{width:50px;height:55px;display:grid;place-content:center;border-radius:10px;text-align:center}.date-block strong,.date-block small{display:block}.date-block strong{font-size:19px}.date-block small{font-size:9px}.date-block.red{color:#ae3543;background:#ffedf0}.date-block.teal{color:#087b73;background:#e5f6f4}.date-block.navy{color:#315b87;background:#ebf2f9}.agenda-item h3{margin:7px 0 3px;font-size:13px}.agenda-item p{margin:0 0 8px;color:#758293;font-size:10px}.agenda-item>div>small{color:#8995a2;font-size:9px}.agenda-item>button{border:0;color:#8a96a3;background:transparent}@media(max-width:920px){.deadline-grid{grid-template-columns:1fr}}@media(max-width:580px){.days span{min-height:43px;padding:6px}.calendar{padding:14px}.deadline-grid{display:block}.agenda{margin-top:22px}}
</style>
