<template>
  <div class="page">
    <div class="knowledge-head"><span><i class="fa-solid fa-book-open"></i></span><div><h1>法规知识库</h1><p>从争议问题出发，快速定位法律依据、举证要点和常见裁判口径。</p></div></div>
    <label class="knowledge-search"><i class="fa-solid fa-magnifying-glass"></i><input v-model="query" placeholder="搜索：未签劳动合同、加班费举证、违法解除……"><kbd>Enter</kbd></label>
    <div class="topic-grid"><button v-for="item in topics" :key="item.title" @click="query=item.title"><span :class="item.tone"><i :class="item.icon"></i></span><div><strong>{{item.title}}</strong><small>{{item.count}} 条实务指引</small></div><i class="fa-solid fa-chevron-right"></i></button></div>
    <div class="knowledge-layout">
      <section><div class="section-title"><h2>{{ query ? `“${query}”相关内容` : '常用实务指引' }}</h2><button class="text-button">最近更新</button></div><article v-for="article in filtered" :key="article.title" class="panel article"><div><span>{{article.type}}</span><h3>{{article.title}}</h3><p>{{article.summary}}</p><small>{{article.source}} · 更新于 {{article.date}}</small></div><i class="fa-solid fa-arrow-right"></i></article></section>
      <aside class="panel ai-research"><span><i class="fa-solid fa-wand-magic-sparkles"></i></span><h3>让 AI 帮你查找依据</h3><p>描述案情和争议焦点，AI 会从劳动法律规则出发给出检索路径。结果仅供参考，提交前请核验。</p><div v-for="q in questions" :key="q">{{q}} <i class="fa-solid fa-arrow-right"></i></div><button>开始案情研究</button></aside>
    </div>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue'; const query=ref(''); const topics=[{title:'劳动合同',count:38,tone:'teal',icon:'fa-solid fa-file-contract'},{title:'工资与加班',count:46,tone:'gold',icon:'fa-solid fa-coins'},{title:'解除与补偿',count:41,tone:'red',icon:'fa-solid fa-user-minus'},{title:'工伤待遇',count:29,tone:'navy',icon:'fa-solid fa-kit-medical'}]; const articles=[{type:'举证指引',title:'加班费争议中，劳动者需要准备哪些证据？',summary:'从考勤记录、工作安排、沟通记录和工资结构四类材料建立完整证明链。',source:'劳动争议实务指引',date:'2026-09-10'},{type:'请求权分析',title:'用人单位违法解除时，赔偿金如何计算？',summary:'区分解除合法性、工作年限、月工资基数以及高收入封顶规则。',source:'劳动合同法第 47、87 条',date:'2026-09-08'},{type:'时效提示',title:'劳动仲裁一年时效从什么时候开始计算？',summary:'一般争议与劳动关系存续期间拖欠工资的时效起算规则并不相同。',source:'劳动争议调解仲裁法第 27 条',date:'2026-09-02'}]; const filtered=computed(()=>query.value?articles.filter(a=>`${a.title}${a.summary}`.includes(query.value)):articles); const questions=['公司口头辞退但拒绝出具通知怎么办？','只有微信记录能证明劳动关系吗？','调岗降薪后被迫离职如何主张？']
</script>
<style scoped>.knowledge-head{display:flex;align-items:center;gap:15px;margin-bottom:22px}.knowledge-head>span{width:48px;height:48px;display:grid;place-items:center;border-radius:13px;color:#fff;background:linear-gradient(145deg,#153b5e,#0c716d)}.knowledge-head h1{margin:0 0 5px;font-size:29px}.knowledge-head p{margin:0;color:var(--muted);font-size:13px}.knowledge-search{max-width:900px;height:54px;margin-bottom:24px;padding:0 16px;display:flex;align-items:center;gap:11px;border:1px solid #d8e0e7;border-radius:12px;background:#fff;box-shadow:var(--shadow);color:#7f8b98}.knowledge-search input{flex:1;border:0;outline:0;font-size:14px}.knowledge-search kbd{padding:3px 7px;border:1px solid var(--line);border-radius:5px;background:#f6f8fa;font-size:9px}.topic-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:28px}.topic-grid button{padding:15px;display:grid;grid-template-columns:39px 1fr auto;align-items:center;gap:11px;border:1px solid var(--line);border-radius:12px;background:#fff;text-align:left}.topic-grid button>span{width:38px;height:38px;display:grid;place-items:center;border-radius:10px}.topic-grid .teal{color:#087c73;background:#e5f6f4}.topic-grid .gold{color:#9b6817;background:#fff4df}.topic-grid .red{color:#b33b48;background:#ffedf0}.topic-grid .navy{color:#315d8a;background:#eaf1f8}.topic-grid strong,.topic-grid small{display:block}.topic-grid strong{font-size:12px}.topic-grid small{margin-top:3px;color:#8994a1;font-size:9px}.topic-grid button>i{color:#a7b0b9;font-size:10px}.knowledge-layout{display:grid;grid-template-columns:1fr 300px;gap:20px}.article{margin-bottom:10px;padding:19px 20px;display:flex;align-items:center;justify-content:space-between;box-shadow:none}.article span{color:#0e786f;font-size:9px;font-weight:700}.article h3{margin:5px 0 7px;font-size:14px}.article p{margin:0 0 8px;color:#6f7d8d;font-size:10px}.article small{color:#99a2ac;font-size:9px}.article>i{color:#9ca7b2}.ai-research{align-self:start;padding:22px;background:linear-gradient(180deg,#fff,#f3f8f8)}.ai-research>span{width:39px;height:39px;display:grid;place-items:center;border-radius:10px;color:#fff;background:#0d7b73}.ai-research h3{margin:14px 0 7px;font-size:15px}.ai-research p{margin:0 0 16px;color:#6d7b8b;font-size:10px;line-height:1.7}.ai-research>div{padding:10px 0;display:flex;justify-content:space-between;border-top:1px solid var(--line);color:#4f5f71;font-size:10px}.ai-research>div i{color:#9aa4ae}.ai-research button{width:100%;margin-top:14px;padding:10px;border:0;border-radius:8px;color:#fff;background:#0f766e;font-size:11px;font-weight:700}@media(max-width:920px){.topic-grid{grid-template-columns:repeat(2,1fr)}.knowledge-layout{grid-template-columns:1fr}.ai-research{display:none}}@media(max-width:540px){.topic-grid{grid-template-columns:1fr}.knowledge-head p{display:none}.knowledge-search kbd{display:none}}
</style>
